import Head from 'next/head'
import Navbar from '../components/Navbar'
import Jumbotron from '../components/Jumbotron'
import styles from '../styles/Home.module.css'
import Image from 'next/image'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tramanda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tramanda-logo-dark.svg" />
      </Head>
      <Navbar></Navbar>
      <Jumbotron></Jumbotron>
      
    </div>
  )
}
